from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


def write_report(output_dir: str, report: Any, verbose: bool = False):
    path = Path(output_dir)
    path.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    md = _build_markdown(report)
    md_path = path / f"smoke_report_{timestamp}.md"
    md_path.write_text(md)
    logger.info("Report written to %s", md_path)

    jsonl = _build_jsonl(report)
    jsonl_path = path / f"smoke_log_{timestamp}.jsonl"
    jsonl_path.write_text(jsonl)
    logger.info("Interaction log written to %s", jsonl_path)

    if verbose:
        print("\n" + md)


def _build_markdown(report: Any) -> str:
    lines: list[str] = []
    lines.append("# Smoke Suite Results")
    lines.append("")
    lines.append(f"- **Date**: {report.timestamp}")
    lines.append(f"- **Model**: {report.model}")
    lines.append(f"- **Total**: {report.total_tests} tests, "
                 f"{report.total_passed} passed, "
                 f"{report.total_failed} failed "
                 f"({report.pass_rate:.1f}%)")
    lines.append(f"- **Duration**: {_fmt_duration(report.total_duration_ms)}")
    lines.append("")

    for suite in report.suites:
        rate = (suite.passed / suite.total * 100) if suite.total else 0
        lines.append(f"## {suite.category.title()}: {suite.passed}/{suite.total} ({rate:.1f}%)")
        lines.append("")

        failed = [r for r in suite.results if not r.passed]
        if failed:
            lines.append("### Failures")
            lines.append("")
            lines.append("| Test | Error | Duration |")
            lines.append("|------|-------|----------|")
            for r in failed:
                (r.response_preview or "")[:80]
                err = (r.error or "")[:120]
                lines.append(f"| {r.name} | {err} | {_fmt_duration(r.duration_ms)} |")
            lines.append("")

        avg_dur = suite.duration_ms / max(suite.total, 1)
        lines.append(f"Average duration per test: {_fmt_duration(int(avg_dur))}")
        lines.append("")

    if not report.suites:
        lines.append("No suites run.")
        lines.append("")

    lines.append("---")
    lines.append("_Generated by nightly smoke suite_")
    return "\n".join(lines)


def _build_jsonl(report: Any) -> str:
    lines: list[str] = []
    for suite in report.suites:
        for r in suite.results:
            record = {
                "timestamp": report.timestamp,
                "category": suite.category,
                "name": r.name,
                "passed": r.passed,
                "duration_ms": r.duration_ms,
                "tool_calls": r.tool_calls,
                "tokens": r.tokens,
                "response": r.response_preview,
                "error": r.error,
            }
            lines.append(json.dumps(record))
    return "\n".join(lines)


def _fmt_duration(ms: int) -> str:
    if ms < 1000:
        return f"{ms}ms"
    seconds = ms / 1000
    if seconds < 60:
        return f"{seconds:.1f}s"
    minutes = int(seconds // 60)
    secs = int(seconds % 60)
    return f"{minutes}m {secs}s"
