# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd()

a = Analysis(
    [str(PROJECT_ROOT / "src" / "__main__.py")],
    pathex=[str(PROJECT_ROOT)],
    binaries=[],
    datas=[],
    hiddenimports=[
        "dotenv",
        "yaml",
        "uvicorn",
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.protocols",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets.auto",
        "fastapi",
        "sse_starlette",
        "aiosqlite",
        "httpx",
        "chromadb",
        "chromadb.api",
        "chromadb.api.fastapi",
        "chromadb.telemetry",
        "chromadb.telemetry.posthog",
        "duckdb",
        "sqlite_vec",
        "cryptography",
        "imap_tools",
        "apscheduler",
        "apscheduler.triggers",
        "apscheduler.triggers.interval",
        "html2text",
        "sentence_transformers",
        "tiktoken",
        "prompt_toolkit",
        "rich",
        "multipart",
        "pydantic",
        "pydantic_settings",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "PIL",
        "cv2",
        "tensorflow",
        "torch",
        "notebook",
        "jupyter",
        "ipython",
        "test",
        "unittest",
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="ea",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
